#!/usr/bin/env python

"""Amulet tests on a basic barbican deploy on focal-victoria for keystone v3.
"""

from basic_deployment import SoftHSMBasicDeployment

if __name__ == '__main__':
    deployment = SoftHSMBasicDeployment(series='focal', keystone_version=3,
                                        openstack='cloud:focal-victoria',
                                        source='cloud:focal-victoria')
    deployment.run_tests()
