#!/usr/bin/env python

"""Amulet tests on a basic barbican deploy on focal-ussuri for keystone v3.
"""

from basic_deployment import SoftHSMBasicDeployment

if __name__ == '__main__':
    deployment = SoftHSMBasicDeployment(series='focal', keystone_version=3)
    deployment.run_tests()
