#!/usr/bin/env python

"""Amulet tests on a basic aodh deployment on cosmic-rocky for keystone v3.
"""

from basic_deployment import SoftHSMBasicDeployment

if __name__ == '__main__':
    deployment = SoftHSMBasicDeployment(series='cosmic', keystone_version=3)
    deployment.run_tests()
