#!/usr/bin/env python

"""Amulet tests on a basic barbican deploy on bionic-ussuri for keystone v3.
"""

from basic_deployment import SoftHSMBasicDeployment

if __name__ == '__main__':
    deployment = SoftHSMBasicDeployment(series='bionic', keystone_version=3,
                                        openstack='cloud:bionic-ussuri',
                                        source='cloud:bionic-ussuri')
    deployment.run_tests()
