#!/usr/bin/env python

"""Amulet tests on a basic barbican deploy on bionic-stein for keystone v3.
"""

from basic_deployment import SoftHSMBasicDeployment

if __name__ == '__main__':
    deployment = SoftHSMBasicDeployment(series='bionic', keystone_version=3,
                                        openstack='cloud:bionic-stein',
                                        source='cloud:bionic-stein')
    deployment.run_tests()
