#!/usr/bin/env python

"""Amulet tests on a basic aodh deployment on zesty-ocata for keystone v3.
"""

from basic_deployment import SoftHSMBasicDeployment

if __name__ == '__main__':
    deployment = SoftHSMBasicDeployment(series='zesty', keystone_version=3)
    deployment.run_tests()
