#!/usr/bin/env python

"""Amulet tests on a basic aodh deployment on bionic-queens for keystone v3.
"""

from basic_deployment import SoftHSMBasicDeployment

if __name__ == '__main__':
    deployment = SoftHSMBasicDeployment(series='bionic', keystone_version=3)
    deployment.run_tests()
