#!/usr/bin/env python

"""Amulet tests on a basic barbican deploy on bionic-stein for keystone v3.
"""

from basic_deployment import SoftHSMBasicDeployment

if __name__ == '__main__':
    deployment = SoftHSMBasicDeployment(series='disco', keystone_version=3)
    deployment.run_tests()
